[SERVICE]
    Flush         1
    Log_Level     info
    Daemon        off

[INPUT]
    Name          systemd
    Tag           gce.journal.*
    Read_From_Tail Off

[OUTPUT]
    Name          opentelemetry
    Match         *
    Host          127.0.0.1
    Port          4318
    Logs_uri      /v1/logs
    Log_response_payload True
